// Verified industry events with sourced facts.
// Each event = canonical record. Used by /events index and /knowledge/potato-expo-2026 reference.

export const REGIONS = ["All", "Africa", "Americas", "Asia & Pacific", "Europe", "Global / rotating"];
export const AUDIENCES = ["All audiences", "Industry & trade", "Research & policy", "Equipment & agronomy"];
export const FREQUENCIES = ["All cadences", "Annual", "Biennial", "Triennial"];

// Sort key: ISO YYYY-MM-DD of next confirmed edition. null = unknown / not announced.
export const EVENTS = [
  {
    slug: "potato-europe-2026",
    name: "Potato Europe",
    organizer: "Potato Europe (rotating national hosts)",
    frequency: "Annual",
    region: "Europe",
    country: "Germany (2026)",
    venue: "Rittergut Gestorf 1, Springe (Lower Saxony)",
    nextEditionLabel: "9–10 September 2026",
    nextDateISO: "2026-09-09",
    rotation: "DE 2026 · BE 2027 · FR 2028 · NL 2029",
    scale: "Outdoor exhibition; equipment demos + variety trials",
    focus: "Equipment, varieties, agronomy",
    audience: "Equipment & agronomy",
    officialUrl: "https://www.potatoeurope.com/",
    deepDive: null,
    notes: "Rotates between Netherlands, Belgium, Germany, France (4-country cycle).",
  },
  {
    slug: "wpc-2026-kenya",
    name: "World Potato Congress (WPC) 2026",
    organizer: "World Potato Congress Inc., hosted by NPCK + FreshCrop Limited",
    frequency: "Biennial (since 2022; previously triennial)",
    region: "Africa",
    country: "Kenya",
    venue: "Naivasha — Sawela Lodges, Lake Naivasha",
    nextEditionLabel: "October 2026",
    nextDateISO: "2026-10-26",
    rotation: "Global rotation; first time held in East Africa",
    scale: "1,000+ delegates from 60+ countries",
    focus: "Global research, policy, trade",
    audience: "Research & policy",
    officialUrl: "https://wpc2026kenya.com/",
    deepDive: "/knowledge/potato-expo-2026",
    notes: "Theme: Global Potato Partnership for Enhanced Food Systems, Nutrition Security and Trade. Abstract deadline 20 May; early registration 1 July. Next: WPC 2028 in Ghent, Belgium.",
  },
  {
    slug: "interpom-2026",
    name: "Interpom",
    organizer: "Interpom (Kortrijk Xpo)",
    frequency: "Biennial",
    region: "Europe",
    country: "Belgium",
    venue: "Kortrijk Xpo, Doorniksesteenweg 216, 8500 Kortrijk (35,000 m² indoor)",
    nextEditionLabel: "29 November – 1 December 2026",
    nextDateISO: "2026-11-29",
    rotation: null,
    scale: "332 exhibitors from 15 countries; 24,000 visitors from 60 countries",
    focus: "Full potato supply chain — cultivation, processing, equipment, packaging, trade",
    audience: "Industry & trade",
    officialUrl: "https://www.interpom.be/",
    deepDive: null,
    notes: "23rd edition. One of the world's two largest potato-processing trade shows.",
  },
  {
    slug: "global-potato-summit-2026",
    name: "Global Potato Summit (GPS)",
    organizer: "Media Today Pvt. Ltd.",
    frequency: "Annual",
    region: "Asia & Pacific",
    country: "India",
    venue: "Mahatma Mandir Convention & Exhibition Centre, Gandhinagar, Gujarat",
    nextEditionLabel: "16–17 December 2026",
    nextDateISO: "2026-12-16",
    rotation: null,
    scale: "10,000+ visitors at inaugural; 15,000 expected for 2026; 200+ exhibitors; 15+ countries",
    focus: "Global trade, value chain, seed systems, cold chain, sustainability, food security",
    audience: "Industry & trade",
    officialUrl: "https://globalpotatosummit.com/",
    deepDive: "/knowledge/potato-expo-2026",
    notes: "2nd Edition (GPS 2026). Inaugural edition was GPS 2025.",
  },
  {
    slug: "potato-expo-2027",
    name: "Potato Expo (NPC)",
    organizer: "National Potato Council (NPC), USA",
    frequency: "Annual",
    region: "Americas",
    country: "United States",
    venue: "Rotating major US convention cities (recent: Las Vegas, Anaheim, Orlando, Austin)",
    nextEditionLabel: "Mid-January 2027 (TBA)",
    nextDateISO: "2027-01-15",
    rotation: null,
    scale: "~2,000+ attendees; 150–200 exhibitors",
    focus: "US industry trade — growers, processors, suppliers",
    audience: "Industry & trade",
    officialUrl: "https://www.potato-expo.com/",
    deepDive: "/knowledge/potato-expo-2026",
    notes: "Largest annual North American potato event. Founded 1948 (NPC).",
  },
  {
    slug: "british-potato-event-2027",
    name: "British Potato (BP) Event 2027",
    organizer: "Warners Group Publications",
    frequency: "Biennial",
    region: "Europe",
    country: "United Kingdom",
    venue: "United Kingdom (TBA)",
    nextEditionLabel: "2027 (TBA)",
    nextDateISO: "2027-11-01",
    rotation: null,
    scale: "Trade show",
    focus: "UK growers + processors",
    audience: "Industry & trade",
    officialUrl: "https://britishpotato.co.uk/",
    deepDive: null,
    notes: "British Potato Industry Event and British Potato Industry Awards held every other year.",
  },
  {
    slug: "eapr-triennial",
    name: "European Potato Congress / EAPR",
    organizer: "European Association for Potato Research (EAPR)",
    frequency: "Triennial",
    region: "Europe",
    country: "European rotation",
    venue: "European rotation (research-led)",
    nextEditionLabel: "Triennial cycle — see eapr.net for next edition",
    nextDateISO: null,
    rotation: "European rotation",
    scale: "Research-heavy; EAPR member-led",
    focus: "Academic + breeding + R&D",
    audience: "Research & policy",
    officialUrl: "https://eapr.net/",
    deepDive: null,
    notes: "EAPR is the European research association covering potato breeding, agronomy, pathology, and physiology.",
  },
  {
    slug: "appc-asia-pacific",
    name: "Asia Pacific Potato Conference (APPC)",
    organizer: "Asia Pacific potato research network",
    frequency: "Triennial",
    region: "Asia & Pacific",
    country: "Asia-Pacific rotation",
    venue: "Asia-Pacific rotation",
    nextEditionLabel: "Triennial cycle — next edition TBA",
    nextDateISO: null,
    rotation: "Asia-Pacific rotation",
    scale: "300–500 attendees",
    focus: "Research + policy",
    audience: "Research & policy",
    officialUrl: null,
    deepDive: null,
    notes: "Regional research conference. Recent editions held in India and China.",
  },
];

// Sorted: events with confirmed dates (ascending), then events without confirmed dates.
export const EVENTS_BY_DATE = [...EVENTS].sort((a, b) => {
  if (a.nextDateISO && b.nextDateISO) return a.nextDateISO.localeCompare(b.nextDateISO);
  if (a.nextDateISO && !b.nextDateISO) return -1;
  if (!a.nextDateISO && b.nextDateISO) return 1;
  return a.name.localeCompare(b.name);
});
